"""
RAG tool for agent workflows.
Provides document question-answering capabilities.
"""

from typing import Dict, Any, Tuple
from app.core.logging import setup_logger
from app.rag.retrieval.search import search
from app.rag.qa.answer import generate_answer

logger = setup_logger()


def ask_document(question: str, max_chunks: int = 3) -> Tuple[str, Dict]:
    """
    Ask a question about ingested documents using RAG.
    
    Args:
        question: The question to ask about the documents
        max_chunks: Maximum number of context chunks to retrieve (default: 3)
        
    Returns:
        Tuple of (answer_str, telemetry_dict):
            answer_str: The answer generated by the LLM based on document context
            telemetry_dict: Execution metadata (latency, cache hits, confidence, etc.)
        
    Example:
        answer, meta = ask_document("What are the key findings in the research paper?")
    """
    try:
        logger.info(f"RAG tool processing question: '{question[:50]}...'")
        
        # Retrieve relevant chunks - now returns tuple with telemetry
        top_k = max_chunks if max_chunks else 5
        results, retrieval_telemetry = search(question, top_k=top_k)
        
        if not results:
            logger.warning("No relevant documents found")
            telemetry = {
                "error_class": "NO_RESULTS",
                "mode": "safe_none",
                **retrieval_telemetry
            }
            return "No relevant information found in the document knowledge base. Please ingest documents first.", telemetry
        
        logger.info(f"Retrieved {len(results)} chunks for question")
        
        # Generate answer - now returns tuple with telemetry
        answer_data, answer_telemetry = generate_answer(question, results, retrieval_telemetry)
        answer = answer_data.get("answer", "No answer generated")
        
        # Merge telemetry from both stages
        combined_telemetry = {**retrieval_telemetry, **answer_telemetry}
        
        # Pass through user_message if provided by RAG layer
        if "user_message" in answer_data:
            combined_telemetry["user_message"] = answer_data["user_message"]
        
        logger.info(f"RAG tool answered question successfully mode={combined_telemetry.get('mode')} confidence_path={combined_telemetry.get('confidence_path')} answer_status={combined_telemetry.get('answer_status')}")
        return answer, combined_telemetry
        
    except ValueError as e:
        error_msg = str(e)
        logger.error(f"RAG tool validation error: {error_msg}")
        telemetry = {"error_class": "VALIDATION_ERROR", "mode": "error"}
        return f"Configuration error: {error_msg}", telemetry
    except Exception as e:
        error_msg = str(e)
        logger.error(f"RAG tool error: {error_msg}")
        telemetry = {"error_class": "UNKNOWN_ERROR", "mode": "error"}
        return f"Error generating answer: {error_msg}", telemetry


def get_rag_tool_definition() -> Dict[str, Any]:
    """
    Get the tool definition for Google AgentKit.
    
    Returns:
        dict: Tool definition with name, description, and parameters
    """
    return {
        "name": "ask_document",
        "description": (
            "Search and retrieve information from ingested documents. "
            "ALWAYS use this tool for ANY question about: documents, text content, information, "
            "summaries, key points, findings, research, papers, PDFs, or any content-related query. "
            "This tool searches the document knowledge base and returns relevant information. "
            "DO NOT ask for document name - just pass the question directly."
        ),
        "parameters": {
            "type": "object",
            "properties": {
                "question": {
                    "type": "string",
                    "description": "The question to ask about the documents"
                },
                "max_chunks": {
                    "type": "integer",
                    "description": "Maximum number of context chunks to retrieve (default: 3)",
                    "default": 3
                }
            },
            "required": ["question"]
        }
    }
